### ISSUE TITLE
USER CRUD

### ISSUE THREAD

**Issue by oraffdev** [IFRS-Projects/ProjetoWeb_3T_2023-raff#1]
# Create the user CRUD

## **To-Do**

- [x] Create endpoints
- [x] Create endpoits logic
- [ ] Manage routes access with Auth Guard
- [x] Test endpoits with Jest

**Comment by oraffdev** [comment]
not necessary  auth guard for this routes
