### ISSUE TITLE
LIST OF MOVIES

### ISSUE THREAD

**Issue by oraffdev** [IFRS-Projects/ProjetoWeb_3T_2023-raff#9]
### The list of Movies 
The endpoint of the movie list returns a set of movies in **descending** order

### To-do

- [ ] List movies ( **ADMIN ONLY**  ->  DESC )
- [ ] List Movies (  **ADMIN ONLY** -> ASC )
- [ ] View ranking ( **ADMIN ONLY**  -> list movies on another screen ( DESC && ASC) )
- [ ] View ranking of like/deslike ( **USER** -> DESC && ASC) 

### Recomendations
 
- view only for now
- user should list only the movies they liked/disliked
- to sort between DESC and ASC just invert the array
